In [11]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [12]:
import os

print(os.listdir('/content'))

['.config', 'netflix_customer_churn(dataset).csv.xls', 'sample_data']

In [13]:
df = pd.read_csv("/content/netflix_customer_churn(dataset).csv.xls")

df.head()

,Customer_ID,Age,Gender,Country,Subscription_Type,Monthly_Fee,Watch_Hours,Favourite_Genre,Months_Subscribed,Payment_Method,Customer_Support_Calls,Satisfaction_Score,Churn
0,C0001,58,Male,India,Premium,649,9,Comedy,16,Credit Card,5,1,Yes
1,C0002,52,Male,Australia,Standard,499,2,Action,2,Credit Card,1,5,Yes
2,C0003,53,Male,Australia,Standard,499,8,Romance,29,Debit Card,0,2,Yes
3,C0004,39,Female,USA,Basic,199,25,Action,22,UPI,3,1,Yes
4,C0005,40,Female,India,Premium,649,15,Action,35,PayPal,0,5,No

In [14]:
df.head()

,Customer_ID,Age,Gender,Country,Subscription_Type,Monthly_Fee,Watch_Hours,Favourite_Genre,Months_Subscribed,Payment_Method,Customer_Support_Calls,Satisfaction_Score,Churn
0,C0001,58,Male,India,Premium,649,9,Comedy,16,Credit Card,5,1,Yes
1,C0002,52,Male,Australia,Standard,499,2,Action,2,Credit Card,1,5,Yes
2,C0003,53,Male,Australia,Standard,499,8,Romance,29,Debit Card,0,2,Yes
3,C0004,39,Female,USA,Basic,199,25,Action,22,UPI,3,1,Yes
4,C0005,40,Female,India,Premium,649,15,Action,35,PayPal,0,5,No

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [16]:
df.shape

(1000, 13)

In [17]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Country', 'Subscription_Type',
       'Monthly_Fee', 'Watch_Hours', 'Favourite_Genre', 'Months_Subscribed',
       'Payment_Method', 'Customer_Support_Calls', 'Satisfaction_Score',
       'Churn'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             1000 non-null   object
 1   Age                     1000 non-null   int64
 2   Gender                  1000 non-null   object
 3   Country                 1000 non-null   object
 4   Subscription_Type       1000 non-null   object
 5   Monthly_Fee             1000 non-null   int64
 6   Watch_Hours             1000 non-null   int64
 7   Favourite_Genre         1000 non-null   object
 8   Months_Subscribed       1000 non-null   int64
 9   Payment_Method          1000 non-null   object
 10  Customer_Support_Calls  1000 non-null   int64
 11  Satisfaction_Score      1000 non-null   int64
 12  Churn                   1000 non-null   object
dtypes: int64(6), object(7)
memory usage: 101.7+ KB

In [19]:
df.isnull().sum()

Customer_ID               0
Age                       0
Gender                    0
Country                   0
Subscription_Type         0
Monthly_Fee               0
Watch_Hours               0
Favourite_Genre           0
Months_Subscribed         0
Payment_Method            0
Customer_Support_Calls    0
Satisfaction_Score        0
Churn                     0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.fillna(method="ffill", inplace=True)

/tmp/ipykernel_3447/173857299.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", inplace=True)

In [22]:
encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])
df["Country"] = encoder.fit_transform(df["Country"])
df["Subscription_Type"] = encoder.fit_transform(df["Subscription_Type"])
df["Favourite_Genre"] = encoder.fit_transform(df["Favourite_Genre"])
df["Payment_Method"] = encoder.fit_transform(df["Payment_Method"])
df["Churn"] = encoder.fit_transform(df["Churn"])

In [23]:
X = df.drop(["Customer_ID", "Churn"], axis=1)

y = df["Churn"]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [25]:
model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [26]:
y_pred = model.predict(X_test)

In [27]:
print("Accuracy :", accuracy_score(y_test, y_pred))

Accuracy : 0.85

In [28]:
print(confusion_matrix(y_test, y_pred))

[[ 54  26]
 [  4 116]]

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.68      0.78        80
           1       0.82      0.97      0.89       120

    accuracy                           0.85       200
   macro avg       0.87      0.82      0.83       200
weighted avg       0.86      0.85      0.84       200

In [32]:
print("="*50)
print("        NETFLIX CUSTOMER CHURN PREDICTION")
print("="*50)

age = int(input("Enter Age: "))
subscription = input("Subscription (Basic/Standard/Premium): ").strip().lower()
monthly_fee = int(input("Monthly Fee: "))
watch_hours = int(input("Watch Hours Per Week: "))
months = int(input("Months Subscribed: "))
support_calls = int(input("Customer Support Calls: "))
satisfaction = int(input("Satisfaction Score (1-5): "))

reasons = []
score = 0

if watch_hours < 5:
    reasons.append("Low Watch Hours")
    score += 1

if satisfaction < 3:
    reasons.append("Low Satisfaction Score")
    score += 1

if support_calls > 3:
    reasons.append("High Customer Support Calls")
    score += 1

if months < 6:
    reasons.append("New Customer")
    score += 1

if subscription == "basic":
    reasons.append("Basic Subscription Plan")
    score += 1

print("\n" + "="*50)

if score >= 3:
    print("Prediction : Customer Will Churn(Not Continue)")
else:
    print("Prediction : Customer Will Continue")

print("\nReasons:")

if len(reasons) == 0:
    print("• Customer has good engagement.")
else:
    for reason in reasons:
        print("•", reason)

print("\nRecommendations:")

if score >= 3:
    print("• Offer a Discount")
    print("• Recommend Popular Movies")
    print("• Send Personalized Notifications")
    print("• Improve Customer Support")
else:
    print("• Continue Personalized Recommendations")
    print("• Reward Loyal Customers")
    print("• Notify About New Releases")

print("="*50)

==================================================
        NETFLIX CUSTOMER CHURN PREDICTION
==================================================
Enter Age: 15
Subscription (Basic/Standard/Premium): basic
Monthly Fee: 200
Watch Hours Per Week: 2
Months Subscribed: 1
Customer Support Calls: 0
Satisfaction Score (1-5): 2

==================================================
Prediction : Customer Will Churn(Not Continue)

Reasons:
• Low Watch Hours
• Low Satisfaction Score
• New Customer
• Basic Subscription Plan

Recommendations:
• Offer a Discount
• Recommend Popular Movies
• Send Personalized Notifications
• Improve Customer Support
==================================================